config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.media.file.field_media_file
    - field.field.media.file.media_tags
    - media.type.file
  module:
    - file
id: media.file.default
targetEntityType: media
bundle: file
mode: default
content:
  field_media_file:
    weight: 0
    settings:
      progress_indicator: throbber
    third_party_settings: {  }
    type: file_generic
    region: content
  media_tags:
    type: entity_reference_autocomplete_tags
    weight: 2
    region: content
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: 1
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  status:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 3
    region: content
    third_party_settings: {  }
hidden:
  created: true
  path: true
  uid: true
