<?php

/**
 * @file
 * Support for videos as media entities in Bene.
 */

use Drupal\media\MediaInterface;
use Drupal\bene_media\OverrideHelper as Override;
use Drupal\bene_media_video\Plugin\media\Source\Video;

/**
 * Implements hook_media_source_info_alter().
 *
 * @param $sources
 */
function bene_media_video_media_source_info_alter(&$sources) {
  $sources['video_embed_field']['input_match'] = [
    'field_types' => [
      'string',
      'string_long',
      'video_embed_field',
    ],
  ];
  $sources['video_embed_field']['preview'] = TRUE;

  Override::pluginClass($sources['video_embed_field'], Video::class);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function bene_media_video_media_presave(MediaInterface $entity) {
  if ($entity->bundle() == 'video') {
    $entity->automaticallySetThumbnail();
  }
}
