<?php

/**
 * @file
 * Support for Instagram posts as media entities in Bene.
 */

use Drupal\bene_media\OverrideHelper as Override;
use Drupal\bene_media_instagram\Plugin\media\Source\Instagram;

/**
 * Implements hook_media_source_info_alter().
 *
 * @param $sources
 */
function bene_media_instagram_media_source_info_alter(array &$sources) {
  $sources['instagram']['input_match'] = [
    'constraint' => 'InstagramEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $sources['instagram']['preview'] = TRUE;

  Override::pluginClass($sources['instagram'], Instagram::class);
}
